[project]
name = "kosma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.2.0",
    "mkdocs>=1.6.1",
    "pillow>=11.0.0",
    "pytest>=8.3.4",
    "pytz>=2024.2",
]
