[package]
name = "kosma-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "kosma_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module", "abi3-py39"] }
tokio = { version = "1.38", features = ["full"] }
hyper = { version = "1.4", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
bytes = "1.6"
matchit = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
